additionalPrometheusRulesMap:
  rule-name:
    groups:
      - name: kuberly
        rules:
          - alert: HighCPUUtilization
            expr: |
              (
                node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{
                  namespace=~"kuberly|vela-system|k8s-operators-system|ack-system|grafana|istio-system|vault",
                  container!="", 
                  pod!=""
                }
                /
                on(namespace, pod, container) group_left
                kube_pod_container_resource_limits{
                  resource="cpu",
                  namespace=~"kuberly|vela-system|k8s-operators-system|ack-system|grafana|istio-system|vault",
                  container!="", 
                  pod!=""
                }
              ) * 100 > 90
            for: 5m
            labels:
              severity: firing
            annotations:
              description: "High CPU utilization detected for {{ $labels.pod }} in namespace {{ $labels.namespace }} ({{ $value | humanizePercentage }})"
          - alert: HighMemoryUtilization
            expr: |
              (
                container_memory_working_set_bytes{
                  job="kubelet",
                  metrics_path="/metrics/cadvisor",
                  namespace=~"kuberly|vela-system|k8s-operators-system|ack-system|grafana|vault",
                  container!="",
                  image!=""
                }
                /
                on(namespace, pod, container) group_left
                kube_pod_container_resource_limits{
                  resource="memory",
                  namespace=~"kuberly|vela-system|k8s-operators-system|ack-system|grafana|vault",
                  container!="",
                  pod!=""
                }
              ) * 100 > 90
            for: 5m
            labels:
              severity: firing
            annotations:
              description: "High memory utilization detected for {{ $labels.pod }} in namespace {{ $labels.namespace }} ({{ $value | humanizePercentage }})"
          - alert: HealthEndpointDown
            expr: probe_success{instance="${kuberly_health_endpoint}", job="blackbox"} == 0
            for: 1m
            labels:
              severity: firing
              service: "health-endpoint"
            annotations:
              description: "Health endpoint is down or not responding"
          - alert: DeploymentUnavailable
            expr: |
              kube_deployment_status_replicas_available{
                namespace=~"kuberly|vela-system|k8s-operators-system|ack-system|grafana|vault|monitoring"
              } == 0
            for: 1m
            labels:
              severity: firing
            annotations:
              description: "Deployment {{ $labels.deployment }} in namespace {{ $labels.namespace }} has no available replicas."
          - alert: StatefulSetUnavailable
            expr: |
              kube_statefulset_status_replicas_available{
                namespace=~"kuberly|vela-system|k8s-operators-system|ack-system|grafana|vault"
              } == 0
            for: 1m
            labels:
              severity: firing
            annotations:
              description: "StatefulSet {{ $labels.statefulset }} in namespace {{ $labels.namespace }} has no available replicas."
          - alert: PersistentVolumeUsageHigh
            expr: (kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes) * 100 > 80
            for: 5m
            labels:
              severity: firing
            annotations:
              summary: "PVC {{ $labels.persistentvolumeclaim }} in namespace {{ $labels.namespace }} is over 80% full"
              description: |
                PersistentVolumeClaim {{ $labels.persistentvolumeclaim }} in namespace {{ $labels.namespace }} on node {{ $labels.node }} is using more than 80% of its capacity.
alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 20m
        memory: 80Mi
      limits:
        cpu: 20m
        memory: 80Mi
    tolerations:
      - key: "arch/arm"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "on-demand"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    nodeSelector:
      kubernetes.io/arch: arm64
      karpenter.sh/capacity-type: on-demand
      topology.kubernetes.io/zone: "${aws_zone}"
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: "null"
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      routes:
        - receiver: discord-alerts
          matchers:
            - alertname = "HighCPUUtilization"
        - receiver: discord-alerts
          matchers:
            - alertname = "HighMemoryUtilization"
        - receiver: discord-alerts
          matchers:
            - alertname = "HealthEndpointDown"
        - receiver: discord-alerts
          matchers:
            - alertname = "DeploymentUnavailable"
        - receiver: discord-alerts
          matchers:
            - alertname = "StatefulSetUnavailable"
        - receiver: discord-alerts
          matchers:
            - alertname = "PersistentVolumeUsageHigh"
    receivers:
      - name: "null"
      - name: discord-alerts
        discord_configs:
          - webhook_url: '${discord_webhook_url}'
            send_resolved: true
            title: '{{ .CommonLabels.alertname }} - {{ .Status | toUpper }}'
            message: |
              {{ range .Alerts }}
              **Alert:** {{ .Annotations.description }}
              **Severity:** {{ .Labels.severity }}
              **Service:** {{ .Labels.service }}
              **Details:**
              {{ range .Labels.SortedPairs }} • **{{ .Name }}:** {{ .Value }}{{ end }}
              {{ end }}

prometheus:
  prometheusSpec:
    enableAdminAPI: true
    additionalScrapeConfigs:
      - job_name: opencost
        honor_labels: true
        scrape_interval: 1m
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        dns_sd_configs:
          - names:
            - opencost.opencost
            type: 'A'
            port: 9003
      - job_name: blackbox
        metrics_path: /metrics
        scrape_interval: 30s
        scrape_timeout: 10s
        static_configs:
          - targets:
            - ${kuberly_health_endpoint}
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: 'probe_.*'
            action: keep
    retention: ${metrics_retention_period}
    tolerations:
      - key: "arch/arm"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "on-demand"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    nodeSelector:
      kubernetes.io/arch: arm64
      karpenter.sh/capacity-type: on-demand
      topology.kubernetes.io/zone: "${aws_zone}"
    resources:
      requests:
        cpu: 2000m
        memory: 3000Mi
      limits:
        cpu: 2000m
        memory: 3000Mi
    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: ${storage_size}
  additionalPodMonitors:
    - name: istio-cni-pod
      podMetricsEndpoints:
        - port: metrics
          targetPort: 15014
          path: /metrics
          interval: 30s
          scrapeTimeout: 10s
      selector:
        matchLabels:
          k8s-app: istio-cni-node
      namespaceSelector:
        matchNames:
          - istio-system

    - name: istiod-pod
      podMetricsEndpoints:
        - port: http-monitoring
          path: /metrics
          interval: 15s
          scrapeTimeout: 10s
      selector:
        matchLabels:
          app: istiod
      namespaceSelector:
        matchNames:
          - istio-system

    - name: istio-gateways
      podMetricsEndpoints:
        - port: http-envoy-prom
          path: /stats/prometheus
          interval: 15s
          scrapeTimeout: 10s
        - targetPort: 15020
          path: /metrics
          interval: 15s
          scrapeTimeout: 10s
      selector:
        matchLabels:
          app.kubernetes.io/part-of: istio
      namespaceSelector:
        matchNames:
          - istio-system

    - name: istio-ztunnel
      podMetricsEndpoints:
        - targetPort: 15020
          path: /metrics
          interval: 15s
          scrapeTimeout: 10s
      selector:
        matchLabels:
          app: ztunnel
      namespaceSelector:
        matchNames:
          - istio-system

grafana:
  enabled: true
  namespaceOverride: "grafana"
  adminPassword: ${grafana_password}
  podDisruptionBudget:
    minAvailable: 1
  tolerations:
    - key: "arch/arm"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: "on-demand"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/arch: arm64
    karpenter.sh/capacity-type: on-demand
    topology.kubernetes.io/zone: "${aws_zone}"
  resources:
    requests:
      cpu: 300m
      memory: 300Mi
    limits:
      cpu: 300m
      memory: 300Mi
  grafana.ini:
    auth.proxy:
      enabled: true
      auto_sign_up: false
      enable_login_token: true
      disable_signout_menu: true
    security:
      allow_embedding: true
    server:
      domain: ${dns_domain}
      root_url: https://${dns_domain}/grafana
      serve_from_sub_path: true
  serviceAccount:
    create: true
    name: "grafana"
    annotations:
      eks.amazonaws.com/role-arn: ${grafana_cloudwatch_role_arn}
  additionalDataSources:
    - name: CloudWatch
      access: proxy
      editable: false
      jsonData:
        authType: "default"
        defaultRegion: "${aws_region}"
      orgId: 1
      type: cloudwatch
      version: 1
    - name: Loki
      type: loki
      url: http://loki-gateway.monitoring.svc.cluster.local
      jsonData:
        httpHeaderName1: "X-Scope-OrgID"
      secureJsonData:
        httpHeaderValue1: "admins"
    - name: Tempo
      type: tempo
      url: http://tempo-query-frontend.monitoring.svc.cluster.local:3100
      # access: proxy
      # basicAuth: true
      # basicAuthUser: admin
      # secureJsonData:
      #   basicAuthPassword: ${loki_password}
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: true
        editable: false
        options:
          path: /var/lib/grafana/dashboards/default            
  dashboards:
    default:
      aws-rds:
        gnetId: 707
        revision: 1
        datasource: CloudWatch
      aws-redis:
        gnetId: 969
        revision: 1
        datasource: CloudWatch
  persistence:
    enabled: true
    storageClassName: "gp3"
    size: 30Gi

prometheusOperator:
  tolerations:
    - key: "arch/arm"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: "on-demand"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/arch: arm64
    karpenter.sh/capacity-type: on-demand
    topology.kubernetes.io/zone: "${aws_zone}"
  resources:
    requests:
      cpu: 30m
      memory: 51Mi
    limits:
      cpu: 30m
      memory: 51Mi

  prometheusConfigReloader:
    tolerations:
      - key: "arch/arm"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "on-demand"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    nodeSelector:
      kubernetes.io/arch: arm64
      karpenter.sh/capacity-type: on-demand
      topology.kubernetes.io/zone: "${aws_zone}"
    resources:
      requests:
        cpu: 10m
        memory: 20Mi
      limits:
        cpu: 10m
        memory: 20Mi

kube-state-metrics:
  extraArgs:
    - --metric-labels-allowlist=pods=[org_slug,project_slug,env_slug]
  tolerations:
    - key: "arch/arm"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: "on-demand"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/arch: arm64
    karpenter.sh/capacity-type: on-demand
    topology.kubernetes.io/zone: "${aws_zone}"
  resources:
    requests:
      cpu: 50m
      memory: 360Mi
    limits:
      cpu: 50m
      memory: 360Mi

prometheus-node-exporter:
  tolerations:
    - key: "arch/arm"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: "arch/amd"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: "karpenter.sh/disruption"
      value: "disrupting"
      operator: "Equal"
      effect: "NoSchedule"
    - key: "type"
      value: "karpenter"
      operator: "Equal"
      effect: "NoSchedule"
    - key: "on-demand"
      value: "true"
      operator: "Equal"
      effect: "NoSchedule"
    - key: "spot"
      value: "true"
      operator: "Equal"
      effect: "NoSchedule"
    - key: "type"
      operator: "Equal"
      value: "karpenter"
      effect: "NoSchedule"
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Exists
  resources:
    requests:
      cpu: 15m
      memory: 40Mi
    limits:
      cpu: 15m
      memory: 40Mi