apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        app.oam.dev/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"app.oam.dev/publishVersion":"0.0.3","oam.dev/kubevela-version":"v1.9.11"},"labels":{"app.oam.dev/app-revision-hash":"fa43a6b844f503b8","app.oam.dev/appRevision":"syngittest-1762972466507-v7","app.oam.dev/cluster":"050752643586-us-east-2-test3","app.oam.dev/component":"syngittest-1762972466507","app.oam.dev/name":"syngittest-1762972466507","app.oam.dev/namespace":"050752643586-us-east-2-test3","app.oam.dev/resourceType":"WORKLOAD","app.oam.dev/revision":"","kuberly.io/app_id":"0cb48da2-59bc-4041-82a3-b9612bd45f7c","kuberly.io/app_name":"syngittest-1762972466507","kuberly.io/app_type":"repo","kuberly.io/cluster_id":"698b19d1-7582-429f-978f-93837216f510","kuberly.io/container_build_id":"7601cbfa-9488-43bf-9e81-e2a7b52d8275","kuberly.io/container_image_id":"1edadc97-4830-4bd7-ad30-6d3cd0a62e85","kuberly.io/container_registry_id":"0b2550fb-5b25-46c3-b2d5-f2a6323ee0a3","kuberly.io/env_id":"f37ca8ab-1a2a-4409-b9d5-91039711ab33","kuberly.io/env_slug":"test3","kuberly.io/org_id":"efcba3c4-c928-47a2-8054-212676ba5264","kuberly.io/org_slug":"kuberlydevorg-1747916123","kuberly.io/project_id":"b9d0c6cf-6c7d-4fe5-af82-8f2b3b56d045","kuberly.io/project_slug":"kuberlydev","oam.dev/render-hash":"768e3c4ccd738666","workload.oam.dev/type":"deployment-v0.0.4"},"name":"syngittest-1762972466507","namespace":"kuberlydev-test3"},"spec":{"selector":{"matchLabels":{"app.oam.dev/component":"syngittest-1762972466507"}},"template":{"metadata":{"annotations":{"karpenter.sh/do-not-disrupt":"true","reloader.stakater.com/auto":"true"},"labels":{"app.oam.dev/component":"syngittest-1762972466507","app.oam.dev/name":"syngittest-1762972466507","kuberly.io/app_id":"0cb48da2-59bc-4041-82a3-b9612bd45f7c","kuberly.io/app_name":"syngittest-1762972466507","kuberly.io/app_type":"repo","kuberly.io/cluster_id":"698b19d1-7582-429f-978f-93837216f510","kuberly.io/container_build_id":"7601cbfa-9488-43bf-9e81-e2a7b52d8275","kuberly.io/container_image_id":"1edadc97-4830-4bd7-ad30-6d3cd0a62e85","kuberly.io/container_registry_id":"0b2550fb-5b25-46c3-b2d5-f2a6323ee0a3","kuberly.io/env_id":"f37ca8ab-1a2a-4409-b9d5-91039711ab33","kuberly.io/env_slug":"test3","kuberly.io/org_id":"efcba3c4-c928-47a2-8054-212676ba5264","kuberly.io/org_slug":"kuberlydevorg-1747916123","kuberly.io/project_id":"b9d0c6cf-6c7d-4fe5-af82-8f2b3b56d045","kuberly.io/project_slug":"kuberlydev"},"name":"syngittest-1762972466507","namespace":"kuberlydev-test3"},"spec":{"containers":[{"envFrom":[{"secretRef":{"name":"0cb48da2-59bc-4041-82a3-b9612bd45f7c-env-secrets"}}],"image":"050752643586.dkr.ecr.us-east-2.amazonaws.com/test2-1753791287927:test-app-1753791346-aa79bc8789214137e7d4d6276f6dab6f7d585f7b","livenessProbe":{"failureThreshold":3,"initialDelaySeconds":0,"periodSeconds":60,"successThreshold":1,"tcpSocket":{"port":9092},"timeoutSeconds":5},"name":"syngittest-1762972466507","ports":[{"containerPort":9092,"name":"port-9092","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"initialDelaySeconds":0,"periodSeconds":60,"successThreshold":1,"tcpSocket":{"port":9092},"timeoutSeconds":5},"resources":{"limits":{"cpu":"100m","memory":"100Mi"},"requests":{"cpu":"100m","memory":"100Mi"}}}],"nodeSelector":{"karpenter.sh/capacity-type":"spot","kubernetes.io/arch":"arm64"},"tolerations":[{"effect":"NoSchedule","key":"spot","operator":"Equal","value":"true"},{"effect":"NoSchedule","key":"arch/arm64","operator":"Equal","value":"true"}]}}}}'
        app.oam.dev/last-applied-time: "2025-11-13T10:09:49Z"
        app.oam.dev/publishVersion: 0.0.3
        oam.dev/kubevela-version: v1.9.11
    labels:
        app.oam.dev/app-revision-hash: fa43a6b844f503b8
        app.oam.dev/appRevision: syngittest-1762972466507-v7
        app.oam.dev/cluster: 050752643586-us-east-2-test3
        app.oam.dev/component: syngittest-1762972466507
        app.oam.dev/name: syngittest-1762972466507
        app.oam.dev/namespace: 050752643586-us-east-2-test3
        app.oam.dev/resourceType: WORKLOAD
        app.oam.dev/revision: ""
        kuberly.io/app_id: 0cb48da2-59bc-4041-82a3-b9612bd45f7c
        kuberly.io/app_name: syngittest-1762972466507
        kuberly.io/app_type: repo
        kuberly.io/cluster_id: 698b19d1-7582-429f-978f-93837216f510
        kuberly.io/container_build_id: 7601cbfa-9488-43bf-9e81-e2a7b52d8275
        kuberly.io/container_image_id: 1edadc97-4830-4bd7-ad30-6d3cd0a62e85
        kuberly.io/container_registry_id: 0b2550fb-5b25-46c3-b2d5-f2a6323ee0a3
        kuberly.io/env_id: f37ca8ab-1a2a-4409-b9d5-91039711ab33
        kuberly.io/env_slug: test3
        kuberly.io/org_id: efcba3c4-c928-47a2-8054-212676ba5264
        kuberly.io/org_slug: kuberlydevorg-1747916123
        kuberly.io/project_id: b9d0c6cf-6c7d-4fe5-af82-8f2b3b56d045
        kuberly.io/project_slug: kuberlydev
        oam.dev/render-hash: 768e3c4ccd738666
        workload.oam.dev/type: deployment-v0.0.4
    name: syngittest-1762972466507
    namespace: kuberlydev-test3
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app.oam.dev/component: syngittest-1762972466507
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            annotations:
                karpenter.sh/do-not-disrupt: "true"
                reloader.stakater.com/auto: "true"
            creationTimestamp: null
            labels:
                app.oam.dev/component: syngittest-1762972466507
                app.oam.dev/name: syngittest-1762972466507
                kuberly.io/app_id: 0cb48da2-59bc-4041-82a3-b9612bd45f7c
                kuberly.io/app_name: syngittest-1762972466507
                kuberly.io/app_type: repo
                kuberly.io/cluster_id: 698b19d1-7582-429f-978f-93837216f510
                kuberly.io/container_build_id: 7601cbfa-9488-43bf-9e81-e2a7b52d8275
                kuberly.io/container_image_id: 1edadc97-4830-4bd7-ad30-6d3cd0a62e85
                kuberly.io/container_registry_id: 0b2550fb-5b25-46c3-b2d5-f2a6323ee0a3
                kuberly.io/env_id: f37ca8ab-1a2a-4409-b9d5-91039711ab33
                kuberly.io/env_slug: test3
                kuberly.io/org_id: efcba3c4-c928-47a2-8054-212676ba5264
                kuberly.io/org_slug: kuberlydevorg-1747916123
                kuberly.io/project_id: b9d0c6cf-6c7d-4fe5-af82-8f2b3b56d045
                kuberly.io/project_slug: kuberlydev
            name: syngittest-1762972466507
            namespace: kuberlydev-test3
        spec:
            containers:
                - envFrom:
                    - secretRef:
                        name: 0cb48da2-59bc-4041-82a3-b9612bd45f7c-env-secrets
                  image: 050752643586.dkr.ecr.us-east-2.amazonaws.com/test2-1753791287927:test-app-1753791346-aa79bc8789214137e7d4d6276f6dab6f7d585f7b
                  imagePullPolicy: IfNotPresent
                  livenessProbe:
                    failureThreshold: 3
                    periodSeconds: 60
                    successThreshold: 1
                    tcpSocket:
                        port: 9092
                    timeoutSeconds: 5
                  name: syngittest-1762972466507
                  ports:
                    - containerPort: 9092
                      name: port-9092
                      protocol: TCP
                  readinessProbe:
                    failureThreshold: 3
                    periodSeconds: 60
                    successThreshold: 1
                    tcpSocket:
                        port: 9092
                    timeoutSeconds: 5
                  resources:
                    limits:
                        cpu: 100m
                        memory: 100Mi
                    requests:
                        cpu: 100m
                        memory: 100Mi
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            nodeSelector:
                karpenter.sh/capacity-type: spot
                kubernetes.io/arch: arm64
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            tolerations:
                - effect: NoSchedule
                  key: spot
                  operator: Equal
                  value: "true"
                - effect: NoSchedule
                  key: arch/arm64
                  operator: Equal
                  value: "true"
